title: Ziyu.Su Page
email: zxin.suzhou@gmail.com
description: "个人博客"
baseurl: "/api"
url: "https://zxin-git.github.io"
twitter_username: jekyllrb
github_username:  zxin-git

# Build settings
theme: minima
plugins:
  - jekyll-feed
